# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimage',
            name='part1',
            field=models.FileField(default=datetime.datetime(2016, 7, 22, 15, 34, 44, 831998, tzinfo=utc), upload_to='static/img/show/home'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeimage',
            name='part2',
            field=models.FileField(default=datetime.datetime(2016, 7, 22, 15, 35, 5, 64137, tzinfo=utc), upload_to='static/imh/show/home'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='docfile',
            field=models.FileField(upload_to='static/img/show/home'),
        ),
    ]
