# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_auto_20160722_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePart2Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part1', models.FileField(upload_to='static/img/show/home')),
            ],
        ),
        migrations.CreateModel(
            name='HomePart3Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part2', models.FileField(upload_to='static/imh/show/home')),
            ],
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='part1',
        ),
        migrations.RemoveField(
            model_name='homeimage',
            name='part2',
        ),
    ]
