# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_auto_20160722_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePartImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part2_img', models.FileField(upload_to='static/img/show/home')),
                ('part3_img', models.FileField(upload_to='static/imh/show/home')),
            ],
        ),
    ]
