# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_auto_20160723_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSecondImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part2_img', models.FileField(upload_to='static/img/show/home/second')),
            ],
        ),
        migrations.CreateModel(
            name='HomeThirdImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part3_img', models.FileField(upload_to='static/imh/show/home/third')),
            ],
        ),
        migrations.DeleteModel(
            name='HomePartImage',
        ),
    ]
