# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_auto_20160723_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homethirdimage',
            name='part3_img',
            field=models.FileField(upload_to='static/img/show/home/third'),
        ),
    ]
