# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_auto_20160723_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homeImage',
        ),
        migrations.DeleteModel(
            name='HomeSecondImage',
        ),
        migrations.DeleteModel(
            name='HomeThirdImage',
        ),
    ]
